"""empty message

Revision ID: 81f1485ebe3a_
Create Date: 2017-10-08 02:55:28.541232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81f1485ebe3a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Tianqi_xz', sa.Column('day', sa.String(length=64), nullable=True))
    op.add_column('Tianqi_xz', sa.Column('location', sa.String(length=64), nullable=False))
    op.add_column('Tianqi_xz', sa.Column('temperature', sa.String(length=64), nullable=True))
    op.add_column('Tianqi_xz', sa.Column('weather', sa.String(length=64), nullable=True))
    op.drop_constraint('Tianqi_xz_Uuid_key', 'Tianqi_xz', type_='unique')
    op.drop_column('Tianqi_xz', 'Uuid')
    op.drop_column('Tianqi_xz', 'Description')
    op.drop_column('Tianqi_xz', 'Title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Tianqi_xz', sa.Column('Title', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('Tianqi_xz', sa.Column('Description', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('Tianqi_xz', sa.Column('Uuid', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.create_unique_constraint('Tianqi_xz_Uuid_key', 'Tianqi_xz', ['Uuid'])
    op.drop_column('Tianqi_xz', 'weather')
    op.drop_column('Tianqi_xz', 'temperature')
    op.drop_column('Tianqi_xz', 'location')
    op.drop_column('Tianqi_xz', 'day')
    # ### end Alembic commands ###
