"""empty message

Revision ID: 939ec65b30f4
Revises: 0ec353dda931
Create Date: 2017-10-15 16:57:25.032554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '939ec65b30f4'
down_revision = '0ec353dda931'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('weather_xz_location_key', 'weather_xz', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('weather_xz_location_key', 'weather_xz', ['location'])
    # ### end Alembic commands ###
